### ISSUE TITLE
Google products are not "privacy concious"

### ISSUE THREAD

**Issue by JohnDarkhorse** [auctors/free-lunch#1]
Your tagline is "A curated list of free privacy-conscious Windows software, online services and resources."

Google is the *least* privacy conscious entity I'm aware of, and their products & services reflect this position.

The only Google software I'd recommend isn't technically "Google software" at all:  Instead of Chrome browser, you should link to "chromium" (the open source precursor to Chrome).  By default, it is free of most of Google's invasive actions and there are community-provided builds which remove all of the anti-privacy portions.

https://en.wikipedia.org/wiki/Chromium_(web_browser)
https://chromium.woolyss.com/  (various builds of chromium browser)

**Comment by auctors** [comment]
Thanks for your comment!
I have heard of [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium), there is a view that Chrome is much more secure than ungoogled-chromium: https://qua3k.github.io/ungoogled. This is the reason why i added Chrome to my list.
I agree with you, Chrome is not private. I deleted all the anti-privacy software, including Chrome. 
chromium.woolyss.com is a great website that downloads latest stable Chroiumm binaries. Sorry i didn't know that before. It has been added to my list.

**Comment by JohnDarkhorse** [comment]
. . . and now you should probably look up the behavior of the Brave devs and decide what to do with that.

(I do not recommend it to anyone)

1) https://old.reddit.com/r/privacy/comments/nvza9j/brave_is_not_private/
2) https://old.reddit.com/r/privacy/comments/q7vfyy/vivaldi_vs_brave_which_one_is_good_in_terms_of/hgocdc9/

**Comment by auctors** [comment]
> . . . and now you should probably look up the behavior of the Brave devs and decide what to do with that.
> 
> (I do not recommend it to anyone)
> 
>     1. https://old.reddit.com/r/privacy/comments/nvza9j/brave_is_not_private/
> 
>     2. https://old.reddit.com/r/privacy/comments/q7vfyy/vivaldi_vs_brave_which_one_is_good_in_terms_of/hgocdc9/

Brave offers more privacy protections than Firefox right out of the box, it is a private and secure web browser. Just a thought about Brave.

Thank you again for your advice.

**Comment by zakius** [comment]
on the other hand due to severe API limitations Brave can't offer as much control as Quantum does, defaults can only do so much to prevent website breakage and the filtering engine while quite capable lacks GUI to make full use of it

so the thing is: defaults are probably better and has many complex tools, but some things can only be done in Quantum currently as Brave focuses in things that can be set up automatically (which is reasonable as it will affect most of users, not the most picky 1% or less)
