### ISSUE TITLE
MediaInfo, PNGGauntlet, PotPlayer, FastStone, and AndreaMosaic

### ISSUE THREAD

**Issue by Lt-knb** [auctors/free-lunch#18]
MediaInfo shows a detailed list of properties for a lot of formats, and it's also able to tell if a file's extension is correct or renamed.

PNGGauntlet can compress png images to the smallest size possible (especially good for relatively small images and pixel art).

PotPlayer is a great alternative to VLC.

FastStone is a great alternative to IrfanView, but it's non-commercial use.

AndreaMosaic can generate photomosaics by using small images as tiles. Not sure if eligible, because it has a professional version, but it's not that limited

**Comment by auctors** [comment]
> MediaInfo shows a detailed list of properties for a lot of formats, and it's also able to tell if a file's extension is correct or renamed.
> 
> PNGGauntlet can compress png images to the smallest size possible (especially good for relatively small images and pixel art).
> 
> PotPlayer is a great alternative to VLC.
> 
> FastStone is a great alternative to IrfanView, but it's non-commercial use.
> 
> AndreaMosaic can generate photomosaics by using small images as tiles. Not sure if eligible, because it has a professional version, but it's not that limited

Thanks for suggestions!

Added: MediaInfo, FastStone Image Viewer and AndreaMosaic

Regarding PNGGauntlet and PotPlayer, I decided not to add them for the following reasons:
- PNGGauntlet isn't being updated anymore. There are many good open source alternatives to PNGGauntlet.
- PotPlayer is proprietary software and was once bundled with malware. It cannot be trusted.

**Comment by Lt-knb** [comment]
Thanks! I didn't know that about PotPlayer
